# Generated by Django 6.0.2 on 2026-03-03 13:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('company_phone', models.CharField(blank=True, max_length=50)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('rccm', models.CharField(blank=True, max_length=100)),
                ('ninea', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='billing/')),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres de facturation',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Frais supplémentaires')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la zone')),
                ('countries', models.CharField(help_text="Séparés par des virgules. Ex: SN, FR. Utilisez 'ALL' pour le reste du monde.", max_length=300, verbose_name='Codes pays (ISO)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frais de port (€)')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='Livraison gratuite')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'verbose_name_plural': 'Zones de livraison',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_title', models.CharField(blank=True, max_length=200)),
                ('categories_subtitle', models.CharField(blank=True, max_length=200)),
                ('features_title', models.CharField(blank=True, max_length=200)),
                ('features_subtitle', models.CharField(blank=True, max_length=200)),
                ('products_title', models.CharField(blank=True, max_length=200)),
                ('products_subtitle', models.CharField(blank=True, max_length=200)),
                ('promo_title', models.CharField(blank=True, max_length=200)),
                ('promo_subtitle', models.CharField(blank=True, max_length=200)),
                ('promo_image', models.ImageField(blank=True, null=True, upload_to='shop_info/')),
                ('promo_text', models.TextField(blank=True)),
                ('trust_title', models.CharField(blank=True, max_length=200)),
                ('trust_subtitle', models.CharField(blank=True, max_length=200)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='shop_info/')),
                ('about_title', models.CharField(blank=True, max_length=200)),
                ('about_description', models.TextField(blank=True)),
                ('signature', models.CharField(blank=True, max_length=100)),
                ('newsletter_bg_image', models.ImageField(blank=True, null=True, upload_to='newsletter/')),
                ('newsletter_title', models.CharField(default='Rejoignez la communauté', max_length=200)),
                ('newsletter_text', models.CharField(default='Recevez nos conseils...', max_length=255)),
                ('wellness_hero_title', models.CharField(blank=True, default='Sérénité & Équilibre', max_length=255, verbose_name='Titre Hero Bien-être')),
                ('wellness_hero_subtitle', models.CharField(blank=True, default='Retrouvez votre harmonie naturelle...', max_length=255, verbose_name='Sous-titre Hero')),
                ('wellness_hero_bg', models.ImageField(blank=True, null=True, upload_to='shop_info/', verbose_name='Image de fond Hero')),
                ('wellness_philosophy_title', models.CharField(blank=True, default='Notre Philosophie', max_length=255, verbose_name='Titre Philosophie')),
                ('wellness_philosophy_text', models.TextField(blank=True, default='Chez Terra & Pure...', verbose_name='Texte Philosophie')),
                ('wellness_image_break', models.ImageField(blank=True, null=True, upload_to='shop_info/', verbose_name='Image de séparation')),
                ('wellness_cta_title', models.CharField(blank=True, default='Prêt à commencer votre transformation ?', max_length=255, verbose_name="Titre Appel à l'action")),
                ('wellness_cta_text', models.CharField(blank=True, default='Rejoignez notre communauté bien-être.', max_length=255, verbose_name="Texte Appel à l'action")),
                ('about_hero_title', models.CharField(blank=True, default='Retour aux sources', max_length=200)),
                ('about_hero_subtitle', models.CharField(blank=True, default='Une aventure...', max_length=255)),
                ('process_title', models.CharField(blank=True, default='De la plante au pot', max_length=200)),
                ('process_subtitle', models.TextField(blank=True, default='Un processus lent...')),
                ('step1_text', models.CharField(blank=True, default='Cueillette à la main', max_length=100)),
                ('step2_text', models.CharField(blank=True, default='Macération à froid', max_length=100)),
                ('step3_text', models.CharField(blank=True, default='Conditionnement artisanal', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informations Boutique',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Ma Boutique', max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('addresse', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField(verbose_name='Contenu')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Statique',
                'verbose_name_plural': 'Pages Statiques',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(max_length=100, verbose_name='Rôle')),
                ('bio', models.TextField(verbose_name='Biographie courte')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('customer', 'Client'), ('gestionnaire', 'Gestionnaire'), ('admin', 'Administrateur')], default='customer', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.TextField(help_text='Texte court affiché sur la carte')),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='blog/')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='shop.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=20, verbose_name='Code postal')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('is_shipped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.coupon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.paymentmethod')),
                ('shipping_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shippingzone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/')),
                ('total_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_sent', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='shop.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image principale')),
                ('short_description', models.TextField(blank=True, max_length=300, verbose_name='Description courte')),
                ('description', models.TextField(blank=True, verbose_name='Description complète')),
                ('price_ht', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix HT (€)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='TVA (%)')),
                ('video', models.FileField(blank=True, null=True, upload_to='products/videos/', verbose_name='Vidéo du produit (courte)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('ingredients', models.TextField(blank=True, verbose_name='Liste des ingrédients')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_banners/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, help_text="Produit vers lequel le bouton 'Découvrir' redirigera.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Produit associé')),
            ],
            options={
                'verbose_name': 'Bannière',
                'verbose_name_plural': 'Bannières',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='shop.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('income', 'Encaissement'), ('expense', 'Dépense'), ('refund', 'Remboursement'), ('fee', 'Frais plateforme')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la vidéo')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Fichier Vidéo (MP4)')),
                ('video_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Lien Vidéo (YouTube/Vimeo)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/', verbose_name='Miniature (Image)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='shop.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='shop_produc_id_f21274_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='shop_produc_created_ddfb00_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available'], name='shop_produc_availab_47d513_idx'),
        ),
    ]
