# Generated by Django 6.0.2 on 2026-02-14 19:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Bien-être', max_length=50, verbose_name='Catégorie')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'article")),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug (URL)')),
                ('excerpt', models.TextField(help_text='Texte court affiché sur la carte', verbose_name='Extrait (Résumé)')),
                ('content', models.TextField(blank=True, verbose_name='Contenu complet')),
                ('image', models.ImageField(upload_to='blog/', verbose_name="Image de l'article")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_active', models.BooleanField(default=True, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Article de Blog',
                'verbose_name_plural': 'Articles de Blog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: France, International...', max_length=100, verbose_name='Nom de la zone')),
                ('countries', models.CharField(help_text="Séparés par des virgules. Ex: FR,MC. Utilisez 'ALL' pour le reste du monde.", max_length=300, verbose_name='Codes pays (ISO)')),
                ('price', models.FloatField(verbose_name='Frais de port HT (€)')),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'verbose_name_plural': 'Zones de livraison',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1_image', models.ImageField(blank=True, null=True, upload_to='shop_info/')),
                ('banner1_title', models.CharField(blank=True, max_length=200)),
                ('banner1_subtitle', models.CharField(blank=True, max_length=200)),
                ('banner2_image', models.ImageField(blank=True, null=True, upload_to='shop_info/')),
                ('banner2_title', models.CharField(blank=True, max_length=200)),
                ('banner2_subtitle', models.CharField(blank=True, max_length=200)),
                ('banner3_image', models.ImageField(blank=True, null=True, upload_to='shop_info/')),
                ('banner3_title', models.CharField(blank=True, max_length=200)),
                ('banner3_subtitle', models.CharField(blank=True, max_length=200)),
                ('banner4_image', models.ImageField(blank=True, null=True, upload_to='shop_info/')),
                ('banner4_title', models.CharField(blank=True, max_length=200)),
                ('banner4_subtitle', models.CharField(blank=True, max_length=200)),
                ('promo_image', models.ImageField(blank=True, null=True, upload_to='shop_info/')),
                ('promo_text', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='shop_info/')),
                ('about_title', models.CharField(blank=True, max_length=200)),
                ('about_description', models.TextField(blank=True)),
                ('newsletter_bg_image', models.ImageField(blank=True, null=True, upload_to='newsletter/', verbose_name='Image de fond Newsletter')),
                ('newsletter_title', models.CharField(default='Rejoignez la communauté', max_length=200, verbose_name='Titre Newsletter')),
                ('newsletter_text', models.CharField(default='Recevez nos conseils...', max_length=255, verbose_name='Texte Newsletter')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('income', 'Encaissement'), ('expense', 'Dépense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Payé'), ('pending', 'En attente')], default='paid', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('gestionnaire', 'Gestionnaire')], default='customer', max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=250, verbose_name='Adresse')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Code Postal')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('country', models.CharField(default='France', max_length=100, verbose_name='Pays (ISO)')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Frais de port HT')),
                ('payment_method', models.CharField(choices=[('PAYDUNYA', 'Paiement en ligne (PayDunya)'), ('COD', 'Paiement à la livraison')], default='PAYDUNYA', max_length=20, verbose_name='Mode de paiement')),
                ('payment_status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20, verbose_name='Statut de paiement')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total HT (Snapshot)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Mise à jour')),
                ('paid', models.BooleanField(default=False, verbose_name='Payée')),
                ('is_shipped', models.BooleanField(default=False, verbose_name='Expédiée')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('shipping_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.shippingzone', verbose_name='Zone de livraison')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de facturation')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='Fichier PDF')),
                ('total_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total HT')),
                ('total_tva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total TTC')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Envoyée au client')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='shop.order')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('short_description', models.TextField(blank=True, help_text='Affichée sous le prix', max_length=300, verbose_name='Description courte')),
                ('description', models.TextField(blank=True, verbose_name='Description complète')),
                ('price_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix HT (€)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=4, verbose_name='TVA (%)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix HT unitaire')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Image')),
                ('is_main', models.BooleanField(default=False, verbose_name='Image Principale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Produit')),
            ],
            options={
                'ordering': ['-is_main'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('product',), name='unique_main_image_per_product')],
            },
        ),
    ]
