# Generated by Django 6.0.2 on 2026-03-04 00:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingzone',
            name='countries',
        ),
        migrations.AddField(
            model_name='shippingzone',
            name='zones',
            field=models.CharField(default=1, help_text='Séparées par des virgules. Exemple : DAKAR_PLATEAU, THIES', max_length=500, verbose_name='Zones couvertes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Frais de livraison (FCFA)'),
        ),
    ]
