# Generated by Django 6.0.2 on 2026-02-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingzone',
            name='free_shipping',
            field=models.BooleanField(default=False, verbose_name='Livraison gratuite'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='countries',
            field=models.CharField(help_text="Séparés par des virgules. Ex: FR, SN. Utilisez 'ALL' pour le reste du monde.", max_length=300, verbose_name='Codes pays (ISO)'),
        ),
    ]
