# Generated by Django 6.0.2 on 2026-02-18 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_country_order_phone_paymentmethod_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='shop.category'),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
