# Generated by Django 6.0.2 on 2026-03-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_shippingzone_countries_shippingzone_zones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.AddField(
            model_name='order',
            name='zone',
            field=models.CharField(default=1, max_length=50, verbose_name='Zone de livraison'),
            preserve_default=False,
        ),
    ]
