# Generated by Django 6.0.2 on 2026-02-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_blogpost_category_delete_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Liste des ingrédients'),
        ),
    ]
