# Generated by Django 6.0.2 on 2026-03-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
