# Generated by Django 6.0.2 on 2026-03-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_transaction_id_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Passerelle de paiement'),
        ),
    ]
